// Single source for all UI text. Keep every user-facing string here so the
// app can be translated (Georgian) without touching components.
export const strings = {
  appName: 'Restaurant Reservations',
  nav: {
    dashboard: 'Dashboard',
    reservations: 'Reservations',
    calendar: 'Calendar',
    tables: 'Tables',
    guests: 'Guests',
    analytics: 'Analytics',
    settings: 'Settings',
  },
  auth: {
    signInTitle: 'Sign in to your restaurant',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    logout: 'Log out',
    invalidCredentials: 'Invalid email or password.',
  },
  a11y: {
    openMenu: 'Open menu',
    closeDialog: 'Close',
  },
  errors: {
    network: 'Cannot reach the server. Check your connection.',
    forbidden: "You don't have access to this.",
    notFound: 'Not found.',
    unexpected: 'Something went wrong. Please try again.',
  },
  placeholder: {
    comingSoon: 'This page is under construction.',
  },
  status: {
    PENDING: 'Pending',
    CONFIRMED: 'Confirmed',
    SEATED: 'Seated',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
    NO_SHOW: 'No-show',
  },
  common: {
    retry: 'Retry',
    today: 'Today',
    previousDay: 'Previous day',
    nextDay: 'Next day',
  },
  reservations: {
    colTime: 'Time',
    colGuest: 'Guest',
    colPhone: 'Phone',
    colParty: 'Party',
    colTable: 'Table',
    colStatus: 'Status',
    empty: 'No reservations for this day.',
    noMatches: 'No reservations match the filters.',
    searchPlaceholder: 'Search guest or phone…',
    statusAll: 'All statuses',
    detailTitle: 'Reservation details',
    detailDate: 'Date',
    detailTime: 'Time',
    detailGuest: 'Guest',
    detailPhone: 'Phone',
    detailParty: 'Party size',
    detailTable: 'Table',
    detailStatus: 'Status',
    detailNotes: 'Notes',
    detailCheckedIn: 'Checked in',
    detailReminder: 'Reminder sent',
    yes: 'Yes',
    no: 'No',
    none: '—',
    newButton: 'New reservation',
    actions: {
      checkIn: 'Check in',
      complete: 'Complete',
      noShow: 'Mark no-show',
      cancel: 'Cancel',
      move: 'Move',
    },
    move: {
      title: 'Move reservation',
      submit: 'Move reservation',
      submitting: 'Moving…',
    },
    form: {
      title: 'New reservation',
      guestName: 'Guest name',
      guestPhone: 'Phone',
      partySize: 'Party size',
      date: 'Date',
      time: 'Time',
      table: 'Table',
      notes: 'Notes',
      pickTimeFirst: 'Choose a date and time to see available tables.',
      noTablesAvailable: 'No tables available for this time.',
      loadTablesFailed: 'Could not load available tables.',
      required: 'Required.',
      partySizeInvalid: 'Must be at least 1.',
      selectTable: 'Select a table.',
      submit: 'Create reservation',
      submitting: 'Creating…',
    },
  },
  calendar: {
    empty: 'No tables or reservations to display for this day.',
  },
  dashboard: {
    statToday: "Today's reservations",
    statUpcoming: 'Upcoming',
    statOccupied: 'Occupied tables',
    statNoShow: 'No-show rate',
    occupancyTitle: 'Table occupancy',
    todayTitle: "Today's reservations",
    upcomingTitle: 'Upcoming reservations',
    emptyTables: 'No tables configured yet.',
    emptyToday: 'No reservations today.',
    emptyUpcoming: 'No upcoming reservations.',
    guestsSuffix: 'guests',
    seatsSuffix: 'seats',
    retry: 'Retry',
  },
  forbiddenPage: {
    title: 'Access denied',
    body: "You don't have permission to view this page.",
    backHome: 'Back to home',
  },
  notFoundPage: {
    title: 'Page not found',
    body: 'The page you are looking for does not exist.',
    backHome: 'Back to home',
  },
} as const
